# Generated by Django 5.0.7 on 2024-11-18 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_detail_image_1_product_detail_image_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='main_image',
        ),
    ]
