# Generated by Django 5.0.7 on 2024-11-28 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
